apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/studylinker/manifest.git
    targetRevision: HEAD
    path: common
  destination:
    server: https://kubernetes.default.svc
    namespace: webservice  # 요청하신 대로 webservice로 지정
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 이미 있어도 안전하게 유지하는 설정

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/studylinker/manifest.git
    path: charts/root-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: webservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # 이미 있어도 안전하게 유지하는 설정
